name: React to Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  add-reaction:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        uses: cli/cli-action@v2
      - name: React with Rocket Emoji
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github.squirrel-girl-preview+json" \
            /repos/${{ github.repository }}/releases/${{ github.event.release.id }}/reactions \
            -f content=rocket
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
