name: Test PHP Versions

on:
  push:
    paths:
      - "**.php"
  pull_request:
    paths:
      - "**.php"

permissions:
  contents: read

jobs:
  test-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [8.1, 8.2, 8.3, 8.4]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Check PHP syntax
        run: find . -name "*.php" -exec php -l {} \;
