name: Update Translations

on:
  push:
    paths:
      - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'

permissions:
  contents: write

jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check if PHP files changed
        id: check_php
        run: |
          changed_php=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.php' || true)
          echo "changed_php=$changed_php" >> $GITHUB_OUTPUT
      - name: Exit if no PHP change
        if: steps.check_php.outputs.changed_php == ''
        run: |
          echo "No PHP files changed, skipping."
          exit 0
      - name: Save old .pot hash
        id: save_old_hash
        run: |
          POT_FILE="languages/rnmoji.pot"
          if [ -f "$POT_FILE" ]; then
            sha256sum $POT_FILE | cut -d ' ' -f1 > old_pot_hash.txt
          else
            echo "" > old_pot_hash.txt
          fi
      - name: Install gettext
        run: sudo apt-get install -y gettext
      - name: Generate .pot file with xgettext
        run: |
          mkdir -p languages
          find . -name '*.php' | xargs xgettext --from-code=UTF-8 --language=PHP --keyword=__ --keyword=_e --keyword=_x --output=languages/rnmoji.pot --force-po --join-existing
      - name: Get new .pot hash
        id: new_hash
        run: |
          sha256sum languages/rnmoji.pot | cut -d ' ' -f1 > new_pot_hash.txt
          cat new_pot_hash.txt
      - name: Compare hashes and update .po files if needed
        run: |
          old_hash=$(cat old_pot_hash.txt)
          new_hash=$(cat new_pot_hash.txt)
          echo "Old POT hash: $old_hash"
          echo "New POT hash: $new_hash"
          if [ "$old_hash" = "$new_hash" ]; then
            echo ".pot file unchanged, no update needed."
            exit 0
          else
            echo ".pot file changed, updating .po files."
            for po in languages/*.po; do
              echo "Merging $po"
              msgmerge --update --backup=none "$po" languages/rnmoji.pot
            done
          fi
      - name: Reset header of .pot file
        run: |
          awk '
            BEGIN { count=0; skipping=1 }
            /^msgid / { count++; if (count==2) skipping=0 }
            skipping == 0 { print }
          ' languages/rnmoji.pot > temp && mv temp languages/rnmoji.pot
          echo -e "#\nmsgid \"\"\nmsgstr \"\"\n\"Content-Type: text/plain; charset=UTF-8\"\n\"Content-Transfer-Encoding: 8bit\"\n" | cat - languages/rnmoji.pot > temp && mv temp languages/rnmoji.pot
      - name: Reset header of all .po files
        run: |
          for po in languages/*.po; do
            awk '
              BEGIN { count=0; skipping=1 }
              /^msgid / { count++; if (count==2) skipping=0 }
              skipping == 0 { print }
            ' "$po" > temp && mv temp "$po"
            echo -e "#\nmsgid \"\"\nmsgstr \"\"\n\"Content-Type: text/plain; charset=UTF-8\"\n\"Content-Transfer-Encoding: 8bit\"\n" | cat - "$po" > temp && mv temp "$po"
          done
      - name: Commit and push changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add languages/*.pot languages/*.po
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update translations (.pot/.po files)"
          git push
